// Code generated from @earendil-works/pi-ai image-models.generated.js. DO NOT EDIT.
//
// Source: image-models.generated.js (32 image models, 1 provider)

package images

import goai "github.com/rcarmo/go-ai"

func RegisterBuiltinImageModels() {
	for i := range builtinImageModels {
		RegisterImageModel(&builtinImageModels[i])
	}
}

var builtinImageModels = []ImagesModel{
	{
		ID:       "black-forest-labs/flux.2-flex",
		Name:     "Black Forest Labs: FLUX.2 Flex",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "black-forest-labs/flux.2-klein-4b",
		Name:     "Black Forest Labs: FLUX.2 Klein 4B",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "black-forest-labs/flux.2-max",
		Name:     "Black Forest Labs: FLUX.2 Max",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "black-forest-labs/flux.2-pro",
		Name:     "Black Forest Labs: FLUX.2 Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "bytedance-seed/seedream-4.5",
		Name:     "ByteDance Seed: Seedream 4.5",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "google/gemini-2.5-flash-image",
		Name:     "Google: Nano Banana (Gemini 2.5 Flash Image)",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 0.3, Output: 2.5, CacheRead: 0.03, CacheWrite: 0.0833333333},
	},
	{
		ID:       "google/gemini-3-pro-image-preview",
		Name:     "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 2, Output: 12, CacheRead: 0.2, CacheWrite: 0.375},
	},
	{
		ID:       "google/gemini-3.1-flash-image-preview",
		Name:     "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 0.5, Output: 3, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "microsoft/mai-image-2.5",
		Name:     "Microsoft: MAI-Image-2.5",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 5, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "openai/gpt-5-image",
		Name:     "OpenAI: GPT-5 Image",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 10, Output: 10, CacheRead: 1.25, CacheWrite: 0},
	},
	{
		ID:       "openai/gpt-5-image-mini",
		Name:     "OpenAI: GPT-5 Image Mini",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 2.5, Output: 2, CacheRead: 0.25, CacheWrite: 0},
	},
	{
		ID:       "openai/gpt-5.4-image-2",
		Name:     "OpenAI: GPT-5.4 Image 2",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     goai.ModelCost{Input: 8, Output: 15, CacheRead: 2, CacheWrite: 0},
	},
	{
		ID:       "openrouter/auto",
		Name:     "Auto Router",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"text", "image"},
		Cost:     goai.ModelCost{Input: -1000000, Output: -1000000, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v3",
		Name:     "Recraft: Recraft V3",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4",
		Name:     "Recraft: Recraft V4",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4-pro",
		Name:     "Recraft: Recraft V4 Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4-pro-vector",
		Name:     "Recraft: Recraft V4 Pro Vector",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4-vector",
		Name:     "Recraft: Recraft V4 Vector",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1",
		Name:     "Recraft: Recraft V4.1",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1-pro",
		Name:     "Recraft: Recraft V4.1 Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1-pro-vector",
		Name:     "Recraft: Recraft V4.1 Pro Vector",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1-utility",
		Name:     "Recraft: Recraft V4.1 Utility",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1-utility-pro",
		Name:     "Recraft: Recraft V4.1 Utility Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "recraft/recraft-v4.1-vector",
		Name:     "Recraft: Recraft V4.1 Vector",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2-fast",
		Name:     "Sourceful: Riverflow V2 Fast",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2-fast-preview",
		Name:     "Sourceful: Riverflow V2 Fast Preview",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2-max-preview",
		Name:     "Sourceful: Riverflow V2 Max Preview",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2-pro",
		Name:     "Sourceful: Riverflow V2 Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2-standard-preview",
		Name:     "Sourceful: Riverflow V2 Standard Preview",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2.5-fast",
		Name:     "Sourceful: Riverflow V2.5 Fast",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "sourceful/riverflow-v2.5-pro",
		Name:     "Sourceful: Riverflow V2.5 Pro",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		ID:       "x-ai/grok-imagine-image-quality",
		Name:     "xAI: Grok Imagine Image Quality",
		Api:      ImagesApi("openrouter-images"),
		Provider: ImagesProvider("openrouter"),
		BaseURL:  "https://openrouter.ai/api/v1",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     goai.ModelCost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
}
