#!/usr/bin/env bun
// generate-models.ts — Parse pi-ai's models.generated.js and emit Go source.
//
// Usage:
//   bun run scripts/generate-models.ts [--input /path/to/models.generated.js] [--output models_generated.go]

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const args = process.argv.slice(2);
let inputPath = "";
let outputPath = resolve(import.meta.dir, "../models_generated.go");

for (let i = 0; i < args.length; i++) {
  if (args[i] === "--input" && args[i + 1]) inputPath = args[++i];
  if (args[i] === "--output" && args[i + 1]) outputPath = args[++i];
}

// Auto-detect pi-ai location
if (!inputPath) {
  const candidates = [
    resolve(import.meta.dir, "../node_modules/@mariozechner/pi-ai/dist/models.generated.js"),
    "/usr/local/lib/bun/install/global/node_modules/@mariozechner/pi-ai/dist/models.generated.js",
  ];
  for (const c of candidates) {
    try {
      readFileSync(c);
      inputPath = c;
      break;
    } catch {}
  }
}

if (!inputPath) {
  console.error("Could not find models.generated.js. Use --input to specify path.");
  process.exit(1);
}

console.log(`Input:  ${inputPath}`);
console.log(`Output: ${outputPath}`);

// Import the models
const mod = await import(inputPath);
const MODELS = mod.MODELS;

// Collect all models flat
interface ModelEntry {
  id: string;
  name: string;
  api: string;
  provider: string;
  baseUrl: string;
  reasoning: boolean;
  input: string[];
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
  contextWindow: number;
  maxTokens: number;
}

const allModels: ModelEntry[] = [];
for (const [provider, models] of Object.entries(MODELS)) {
  for (const [id, model] of Object.entries(models as Record<string, any>)) {
    allModels.push({
      id: model.id || id,
      name: model.name || id,
      api: model.api || "",
      provider: model.provider || provider,
      baseUrl: model.baseUrl || "",
      reasoning: !!model.reasoning,
      input: model.input || ["text"],
      cost: {
        input: model.cost?.input || 0,
        output: model.cost?.output || 0,
        cacheRead: model.cost?.cacheRead || 0,
        cacheWrite: model.cost?.cacheWrite || 0,
      },
      contextWindow: model.contextWindow || 0,
      maxTokens: model.maxTokens || 0,
    });
  }
}

console.log(`Found ${allModels.length} models across ${Object.keys(MODELS).length} providers`);

// Generate Go source
const lines: string[] = [];

lines.push(`// Code generated by scripts/generate-models.ts from @mariozechner/pi-ai. DO NOT EDIT.`);
lines.push(`//`);
lines.push(`// Source: models.generated.js (${allModels.length} models, ${Object.keys(MODELS).length} providers)`);
lines.push(`// Generated: ${new Date().toISOString()}`);
lines.push(``);
lines.push(`package goai`);
lines.push(``);
lines.push(`// RegisterBuiltinModels registers all known models from pi-ai's model registry.`);
lines.push(`// Call this during init() or at program startup to populate the model registry.`);
lines.push(`func RegisterBuiltinModels() {`);
lines.push(`\tfor i := range builtinModels {`);
lines.push(`\t\tRegisterModel(&builtinModels[i])`);
lines.push(`\t}`);
lines.push(`}`);
lines.push(``);
lines.push(`var builtinModels = []Model{`);

for (const m of allModels) {
  const inputArr = m.input.map((i: string) => `"${i}"`).join(", ");
  lines.push(`\t{`);
  lines.push(`\t\tID:            ${JSON.stringify(m.id)},`);
  lines.push(`\t\tName:          ${JSON.stringify(m.name)},`);
  lines.push(`\t\tApi:           ${JSON.stringify(m.api)},`);
  lines.push(`\t\tProvider:      ${JSON.stringify(m.provider)},`);
  lines.push(`\t\tBaseURL:       ${JSON.stringify(m.baseUrl)},`);
  lines.push(`\t\tReasoning:     ${m.reasoning},`);
  lines.push(`\t\tInput:         []string{${inputArr}},`);
  lines.push(`\t\tCost:          ModelCost{Input: ${m.cost.input}, Output: ${m.cost.output}, CacheRead: ${m.cost.cacheRead}, CacheWrite: ${m.cost.cacheWrite}},`);
  lines.push(`\t\tContextWindow: ${m.contextWindow},`);
  lines.push(`\t\tMaxTokens:     ${m.maxTokens},`);
  lines.push(`\t},`);
}

lines.push(`}`);
lines.push(``);

const goSource = lines.join("\n");
writeFileSync(outputPath, goSource);

const sizeKB = (Buffer.byteLength(goSource) / 1024).toFixed(1);
console.log(`Wrote ${outputPath} (${sizeKB} KB, ${lines.length} lines)`);
